name: orders_app
description: "Aplicação Flutter para gerenciamento de pedidos e funcionários com integração API real"
publish_to: 'none'

version: 1.0.2+3

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.2
  
  # Navigation
  go_router: ^15.1.2
  
  # Local Storage
  shared_preferences: ^2.4.10
  
  # HTTP & API
  http: ^1.4.0
  
  # Utils
  intl: ^0.20.2  # Adicionando intl explicitamente
  uuid: ^4.5.1
  crypto: ^3.0.6
  
  # UI Components
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
  
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700

